### ISSUE TITLE
Error while parsing a quoted option

### ISSUE THREAD

**Issue by mvila** [txgruppi/parseargs.js#2]
Thanks for your module but  I get an `"Invalid argument(s)"` error when I try to parse a quoted option.

For example:

```js
parse('hello --name="John Lennon"')
```

I think this way of specifying an option is pretty standard and Node.js handles it with `process.argv`. Would it be complicated to implement it?

**Comment by txgruppi** [comment]
Hi @mvila.

This library was not created to parse cli like arguments. There are several other libraries that can do this for you.

The purpose of this library is to parse input similar to [Redis](https://redis.io/) commands.

One example of use would be to parse a message from a Slack command:

```
/hello "John Lennon"
```

Cheers.

PS: If you remove the `=` sign it should work. `parse('hello --name "John Lennon"')`

**Comment by mvila** [comment]
Thanks for your answer but I am not looking for something like `minimist`, I don't want to go this far. I just need to parse a command line string the same way the shell is doing. For example, if I run:

`node -e "console.log(process.argv)" hello --name="John Lennon"`

I get the following result:

```
[ 
  '/Users/mvila/.nvm/versions/node/v7.5.0/bin/node',
  'hello',
  '--name=John Lennon' 
]
```

Notice how the shell has removed the double-quotes around `John Lennon`. This is the kind of parsing I am looking for but unfortunately I could't find any module doing that. Any idea?

**Comment by txgruppi** [comment]
Maybe `shell-quote`.

```
$ node -e "console.log(require('shell-quote').parse('hello --name=\"John Lennon\"'));"
[ 'hello', '--name=John Lennon' ]
```

**Comment by mvila** [comment]
Wow, this is exactly what I was looking for! Thanks a lot @txgruppi! 😃
